# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True

amp: True # Automatic mixed precision

start_epoch: 0  
end_epoch: 50
warmup_epochs: 5 # warmup start

iter_per_epoch: 8
early_stop_epooch: 20 # early stop patience

print_freq: 10 # print frequency


