# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.experiments_dir}/runs/${cls_mode}/${paths.time_dir}/${task_name}
sweep:
  dir: ${paths.experiments_dir}/multiruns/${cls_mode}/${paths.time_dir}/${task_name}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
