defaults:
  - default

#DATA
data_root: /home/user/Multimodal_Transformer_Glioma/data/TCGA/
label_root: /home/user/Multimodal_Transformer_Glioma/data/TCGA_label.xlsx 

save_dir: null
job_num: '' # /0

task_name: "TCGA"
