defaults:
  - default

#DATA
# data_root: /mai_nas/BYS/brain_metastasis/preprocessed/UCSF
data_root: /mnt/BYS/dataset/UCSF/
label_root: /mai_nas/BYS/brain_metastasis/data/UCSF/UCSF_whole_label.xlsx


save_dir: null
job_num: '' # /0

# radiomics_root: /mai_nas/BYS/brain_metastasis/preprocessed/sev_analysis
# test_radiomics_root: /mai_nas/BYS/brain_metastasis/preprocessed/tcga_analysis

