# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: eval
  - hydra: eval
  - metric: binary
  - model: multimodal_swin_small
  - paths: TCGA

cls_mode: "idh"

best_thres: null

ckpt: null
