# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: eval
  - hydra: eval
  - metric: binary
  - model: multimodal_vit_base_xai
  - paths: internal_eval
  - xai: multimodal_vit_attmap

# task_name: "TCGA" # name of dataset

cls_mode: "idh"

best_thres: null

ckpt: null
