# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: eval
  - hydra: eval
  - metric: binary
  - model: timm_default
  - paths: internal_eval
  - xai: vit_attmap


gpus: 3

task_name: "val" # 'val'' for validation set and 'test' for internal test set

cls_mode: "idh"

best_thres: null

ckpt: null

